name: CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*

jobs:
  test-newton-ubuntu-x86_64:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.0"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Run Tests
        run: uv run --all-extras -m newton.tests --junit-report-xml rspec.xml --coverage --coverage-xml coverage.xml
      - name: Test Summary
        uses: test-summary/action@v2.4
        with:
          paths: "rspec.xml"
          show: "fail"
        if: always()
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@f2dba722c67b86c6caa034178c6e4d35335f6706
        with:
          files: ./rspec.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d
        with:
          env_vars: OS,PYTHON_VERSION
          files: ./coverage.xml
          flags: unittests
